const genres=[['all','All'],['action','Action'],['adventure','Adventure'],['comedy','Comedy'],['drama','Drama'],['fantasy','Fantasy'],['romance','Romance'],['mystery','Mystery'],['horror','Horror'],['scifi','Sci-Fi'],['sports','Sports'],['psychological','Psychological'],['slice','Slice of Life'],['shounen','Shōnen'],['seinen','Seinen'],['shoujo','Shōjo'],['josei','Josei']];
const chips=document.querySelector('#chips'),grid=document.querySelector('#grid'),search=document.querySelector('#search'),sort=document.querySelector('#sort'),status=document.querySelector('#status');
let page=1,current='';
genres.forEach(([v,l])=>{const b=document.createElement('button');b.className='chip'+(v==='all'?' active':'');b.textContent=l;b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');current=v==='all'?'':v;page=1;load();};chips.appendChild(b)});
function episodeText(n){return Number.isFinite(Number(n))&&Number(n)>0?`${n} eps`:'Episodes: Unknown'}
async function load(){grid.innerHTML='<p>Loading live anime… 🌸</p>';const q=new URLSearchParams({page,sort:sort.value,status:status.value});if(current)q.set('genre',current);if(search.value.trim())q.set('search',search.value.trim());try{const r=await fetch('/api/anime?'+q);const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');render(d.data||[]);document.querySelector('#pageText').textContent='Page '+page;document.querySelector('#prev').disabled=page<=1;document.querySelector('#next').disabled=!d.pagination?.has_next_page}catch(e){grid.innerHTML='<p>Could not load anime right now. Try again in a moment.</p>'}}
function render(list){grid.innerHTML=list.length?'':'<p>No anime found.</p>';list.forEach(a=>{const el=document.createElement('article');el.className='anime';const img=a.images?.jpg?.large_image_url||a.images?.jpg?.image_url||'';el.innerHTML=`<div class="poster">${img?`<img loading="lazy" src="${safe(img)}" alt="">`:'<div></div>'}</div><div class="info"><h3>${safe(a.title||'Untitled')}</h3><div class="meta"><span>⭐ ${a.score??'—'}</span><span>${a.year??'—'}</span><span>${episodeText(a.episodes)}</span></div></div>`;grid.appendChild(el)})}
function safe(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.querySelector('#searchBtn').onclick=()=>{page=1;load()};search.addEventListener('keydown',e=>{if(e.key==='Enter'){page=1;load()}});sort.onchange=()=>{page=1;load()};status.onchange=()=>{page=1;load()};document.querySelector('#prev').onclick=()=>{if(page>1){page--;load();scrollTo({top:650,behavior:'smooth'})}};document.querySelector('#next').onclick=()=>{page++;load();scrollTo({top:650,behavior:'smooth'})};
const randomBtn=document.createElement('button');randomBtn.className='random-btn';randomBtn.type='button';randomBtn.textContent='🎲 Surprise Me';const controls=search.closest('form')||search.parentElement;if(controls)controls.appendChild(randomBtn);
randomBtn.onclick=async()=>{randomBtn.disabled=true;randomBtn.textContent='🎲 Finding...';try{const res=await fetch('/api/random?genre='+encodeURIComponent(current));const d=await res.json();if(!res.ok)throw Error(d.error||'Could not find anime');showRandom(d.anime)}catch(e){alert('Could not find a random anime right now. Please try again.')}finally{randomBtn.disabled=false;randomBtn.textContent='🎲 Surprise Me'}};
function showRandom(a){const img=a.images?.jpg?.large_image_url||a.images?.jpg?.image_url||'';let panel=document.querySelector('#randomResult');if(!panel){panel=document.createElement('section');panel.id='randomResult';panel.className='random-result';grid.parentElement.insertBefore(panel,grid)}panel.innerHTML=`<h2>🎲 Your Surprise Anime</h2><article class="anime"><div class="poster">${img?`<img src="${safe(img)}" alt="">`:''}</div><div class="info"><h3>${safe(a.title||'Untitled')}</h3><div class="meta"><span>⭐ ${a.score??'—'}</span><span>${a.year??'—'}</span><span>${episodeText(a.episodes)}</span></div><p>${safe((a.synopsis||'A surprise recommendation from live Kitsu data.').slice(0,360))}</p></div></article>`;panel.scrollIntoView({behavior:'smooth',block:'center'})}
const questions=[['Pick a story mood','action','Mystery','mystery','Comedy','comedy','Emotional','drama'],['Your ideal setting?','fantasy','Fantasy world','fantasy','Modern city','mystery','School life','slice','Sports arena','sports'],['What do you want most?','action','Epic battles','action','Big laughs','comedy','Romance','romance','Mind games','psychological'],['Pick a pace','action','Fast and intense','action','Slow and thoughtful','seinen','Balanced','fantasy'],['Which protagonist sounds best?','shounen','A determined rival-chaser','shounen','A quiet strategist','seinen','A lovable goofball','comedy','A complex antihero','psychological'],['What feeling should the finale leave?','drama','Emotional','drama','Hyped','action','Warm','romance','Mind-blown','mystery'],['Choose a side quest','sports','Tournament arc','sports','Mystery investigation','mystery','Fantasy adventure','fantasy','Everyday life','slice'],['How serious?','comedy','Mostly fun','comedy','A balanced mix','action','Very serious','seinen'],['Which world?','scifi','Future / sci-fi','scifi','Historical / grounded','seinen','Magical','fantasy','Everyday Japan','slice'],['Final vibe','romance','Heartwarming','romance','Adrenaline','action','Dark and psychological','psychological','Friendship and adventure','shounen']];
let qi=0,scores={};const modal=document.querySelector('#quizModal');document.querySelector('#startQuiz').onclick=()=>{qi=0;scores={};modal.hidden=false;showQ()};document.querySelector('#closeQuiz').onclick=()=>modal.hidden=true;
function showQ(){const q=questions[qi];document.querySelector('#qCount').textContent=`QUESTION ${qi+1} / 10`;document.querySelector('#qText').textContent=q[0];const box=document.querySelector('#answers');box.innerHTML='';for(let i=1;i<q.length;i+=2){const b=document.createElement('button');b.className='answer';b.textContent=q[i+1];b.onclick=()=>answer(q[i]);box.appendChild(b)}document.querySelector('#progressBar').style.width=((qi+1)*10)+'%'}
async function answer(taste){scores[taste]=(scores[taste]||0)+1;qi++;if(qi<questions.length){showQ();return}modal.hidden=true;const best=Object.entries(scores).sort((a,b)=>b[1]-a[1])[0][0];await showResult(best)}
async function showResult(best){const r=document.querySelector('#result');r.hidden=false;document.querySelector('#resultTaste').textContent=`Your taste: ${label(best)}`;const box=document.querySelector('#resultCard');box.innerHTML='<p>Finding a live recommendation… 🌸</p>';r.scrollIntoView({behavior:'smooth'});try{const res=await fetch('/api/quiz?taste='+encodeURIComponent(best));const d=await res.json();if(!res.ok)throw Error(d.error);const a=d.anime;const img=a.images?.jpg?.large_image_url||a.images?.jpg?.image_url||'';box.innerHTML=`<article class="anime" style="max-width:300px"><div class="poster">${img?`<img src="${safe(img)}" alt="">`:''}</div><div class="info"><h3>${safe(a.title)}</h3><div class="meta"><span>⭐ ${a.score??'—'}</span><span>${a.year??'—'}</span><span>${episodeText(a.episodes)}</span></div><p>${safe((a.synopsis||'A live Kitsu recommendation based on your quiz result.').slice(0,360))}</p></div></article>`}catch(e){box.innerHTML='<p>We could not fetch your recommendation right now. Please try the quiz again.</p>'}}
function label(x){return {action:'Action',mystery:'Mystery',comedy:'Comedy',drama:'Drama',fantasy:'Fantasy',romance:'Romance',psychological:'Psychological',sports:'Sports',scifi:'Sci-Fi',slice:'Slice of Life',shounen:'Shōnen',seinen:'Seinen',shoujo:'Shōjo',josei:'Josei'}[x]||x}
function petals(n=8){for(let i=0;i<n;i++){const p=document.createElement('i');p.className='petal';p.style.left=Math.random()*100+'vw';p.style.setProperty('--drift',(Math.random()*260-130)+'px');p.style.animationDuration=(5+Math.random()*7)+'s';p.style.animationDelay=(Math.random()*2)+'s';p.style.transform=`scale(${.5+Math.random()*.9})`;document.body.appendChild(p);setTimeout(()=>p.remove(),14000)}}setInterval(()=>petals(3),1800);window.addEventListener('scroll',()=>{if(Math.random()<.35)petals(2)});petals(10);load();