FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY Main.java .

COPY public ./public

RUN javac --add-modules jdk.httpserver Main.java

EXPOSE 8000

CMD ["java", "--add-modules", "jdk.httpserver", "Main"]